version: '3'
services:
  nginx:
    container_name: app-nginx
    image: nginx:1.13
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - service1
      - service2

  service1:
    restart: always
    build: .
    working_dir: /app
    volumes:
      - .:/app
    expose:
      - "8181:8080"
    command: mvn clean spring-boot:run

  service2:
    restart: always
    build: .
    working_dir: /app
    volumes:
      - .:/app
    expose:
      - "8282:8080"
    command: mvn clean spring-boot:run